.TH "Diccionario::iterator" 3 "Viernes, 28 de Diciembre de 2018" "ClaseDiccionario" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Diccionario::iterator \- clase para iterar sobre el diccionario  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Diccionario\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "string \fBoperator*\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBiterator\fP &i)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &i)"
.br
.in -1c
.SS "Amigas"

.in +1c
.ti -1c
.RI "class \fBDiccionario\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
clase para iterar sobre el diccionario 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ClaseDiccionario del código fuente\&.
