.TH "Diccionario.h" 3 "Viernes, 28 de Diciembre de 2018" "ClaseDiccionario" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Diccionario.h \- Fichero cabecera del TDA diccionario\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <set>\fP
.br
\fC#include <vector>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBDiccionario\fP"
.br
.ti -1c
.RI "class \fBDiccionario::iterator\fP"
.br
.RI "clase para iterar sobre el diccionario "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA diccionario\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ClaseDiccionario del código fuente\&.
