.TH "info" 3 "Viernes, 28 de Diciembre de 2018" "ClaseLetras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
info
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBinfo\fP (int apara, int punt)"
.br
.in -1c
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "int \fBapariciones\fP"
.br
.ti -1c
.RI "int \fBpuntuacion\fP"
.br
.in -1c

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ClaseLetras del código fuente\&.
