.TH "Letras::iterator" 3 "Viernes, 28 de Diciembre de 2018" "ClaseLetras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Letras::iterator \- clase para iterar sobre las letras  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <letras\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "pair< const char, \fBinfo\fP > & \fBoperator*\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBiterator\fP &i)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &i)"
.br
.in -1c
.SS "Amigas"

.in +1c
.ti -1c
.RI "class \fBLetras\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
clase para iterar sobre las letras 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ClaseLetras del código fuente\&.
